InvoicingApplication/Controllers/DashboardController.cs
using InvoicingApplication.Data;
using InvoicingApplication.Models;
using InvoicingApplication.Utilis;
using Microsoft.AspNetCore.Mvc;

namespace InvoicingApplication.Controllers
{
    public class DashboardController : Controller
    {
        private readonly LoginDbContext _db;
        SystemUtils systemUtils = new SystemUtils();
        public DashboardController(LoginDbContext db)
        {

            _db = db;
            
        }
        public void RetrieveUserInfo()
        {
            try
            {
                ViewBag.Email = HttpContext.Session.GetString("Email");
                string temp = ViewBag.Email;
                int id = 1;
                int atTheRateIndexValue = temp.IndexOf('@');
                string userName = temp.Substring(0, atTheRateIndexValue);
                ViewBag.userName = userName;
                var UsersInfo = _db.Users.ToList();
                if (UsersInfo == null)
                {
                    id = 1;
                }
                foreach (var users in UsersInfo)
                {
                    if (users.Email == ViewBag.Email)
                    {
                        id = users.Id;
                    }
                }
                ViewBag.Id = id;
            }
            catch (Exception ex)
            {
                ViewBag.Email = "Error-User";
                ViewBag.userName = "Error-User";
                ViewBag.Id = 0;
            }
        }

        public IActionResult DashboardPage()
        {
            RetrieveUserInfo();
            if(ViewBag.Id == 0)
            {
                return NotFound();
            }
            return View();
        }
        public IActionResult ContactUs()
        {
            RetrieveUserInfo();
            return View();
        }
    }
}

InvoicingApplication/Controllers/UserController.cs
using InvoicingApplication.Data;
using InvoicingApplication.Models;
using Microsoft.AspNetCore.Mvc;

namespace InvoicingApplication.Controllers
{
    public class UserController : Controller
    {
        private readonly LoginDbContext _db;

        public UserController(LoginDbContext db)
        {
            _db = db;
        }


        public void RetrieveUserInfo()
        {
            try
            {
                ViewBag.Email = HttpContext.Session.GetString("Email");
                string temp = ViewBag.Email;
                int id = 1;
                int atTheRateIndexValue = temp.IndexOf('@');
                string userName = temp.Substring(0, atTheRateIndexValue);
                ViewBag.userName = userName;
                var UsersInfo = _db.Users.ToList();
                if (UsersInfo == null)
                {
                    id = 1;
                }
                foreach (var users in UsersInfo)
                {
                    if (users.Email == ViewBag.Email)
                    {
                        id = users.Id;
                    }
                }
                ViewBag.Id = id;
            }
            catch (Exception ex)
            {
                ViewBag.Email = "Error-User";
                ViewBag.userName = "Error-User";
                ViewBag.Id = 0;
            }
        }

        public IActionResult Index()
        {
            RetrieveUserInfo();
            IEnumerable<LoginModelClass> ObjUsersInList = _db.Users;
            return View(ObjUsersInList);
        }
        
        //GET
        public IActionResult Edit(int? id)
        {
            RetrieveUserInfo();
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var foundUser = _db.Users.Find(id);
            if (foundUser == null)
            {
                return NotFound();
            }
            return View(foundUser);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(LoginModelClass UpdatedInfo)
        {
            if (ModelState.IsValid)
            {
                _db.Users.Update(UpdatedInfo);
                _db.SaveChanges();
                TempData["UpdateSucess"] = "Updated successfully , Please re-login again";
                return RedirectToAction("LoginPage", "Identity");
            }
            return View(UpdatedInfo);
        }
        //GET
        public IActionResult CreateUser()
        {
            RetrieveUserInfo();
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateUser(LoginModelClass UpdatedInfo)
        {

            if (ModelState.IsValid)
            {
                _db.Users.Add(UpdatedInfo);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        //GET
        public IActionResult EditOtherUser(int? id)
        {
            RetrieveUserInfo();
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var foundUser = _db.Users.Find(id);
            if (foundUser == null)
            {
                return NotFound();
            }
            return View(foundUser);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditOtherUser(LoginModelClass UpdatedInfo)
        {
            if (ModelState.IsValid)
            {
                _db.Users.Update(UpdatedInfo);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(UpdatedInfo);
        }

        //GET
        public IActionResult Delete(int? id)
        {
            RetrieveUserInfo();
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var UserFromDb = _db.Users.Find(id);
            if (UserFromDb == null)
            {
                return NotFound();
            }
            return View(UserFromDb);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePOST(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var UserFromDb = _db.Users.Find(id);
            if (UserFromDb == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Users.Remove(UserFromDb);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(UserFromDb);
        }
    }
}

InvoicingApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InvoicingApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InvoicingApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InvoicingApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - InvoicingApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InvoicingApplication/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InvoicingApplication</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InvoicingApplication.styles.css" asp-append-version="true" />*@
    <link rel="icon" type="image/png" href="~/LoginPage/images/icons/favicon.ico" />
    <link rel="stylesheet" type="text/css" href="~/LoginPage/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/LoginPage/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/LoginPage/fonts/iconic/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" type="text/css" href="~/LoginPage/vendor/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="~/LoginPage/vendor/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="~/LoginPage/vendor/animsition/css/animsition.min.css">
    <link rel="stylesheet" type="text/css" href="~/LoginPage/vendor/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/LoginPage/vendor/daterangepicker/daterangepicker.css">
    <link rel="stylesheet" type="text/css" href="~/LoginPage/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/LoginPage/css/main.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body onload="window.history.forward();">
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>
    
    
    <script src="~/LoginPage/vendor/jquery/jquery-3.2.1.min.js"></script>
    <script src="~/LoginPage/vendor/animsition/js/animsition.min.js"></script>
    <script src="~/LoginPage/vendor/bootstrap/js/popper.js"></script>
    <script src="~/LoginPage/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/LoginPage/vendor/select2/select2.min.js"></script>
    <script src="~/LoginPage/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/LoginPage/vendor/daterangepicker/daterangepicker.js"></script>
    <script src="~/LoginPage/vendor/countdowntime/countdowntime.js"></script>
    <script src="~/LoginPage/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InvoicingApplication/Views/Shared/_Notification.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

@if (TempData["WrongPassword"] != null)
{
    <script type="text/javascript">
        toastr.error('@TempData["WrongPassword"]', { timeOut: 5000 });
    </script>
}
@if (TempData["UserNotFound"] != null)
{
    <script type="text/javascript">
        toastr.error('@TempData["UserNotFound"]', { timeOut: 5000 });
    </script>
}
@if (TempData["UpdateSucess"] != null)
{
    <script type="text/javascript">
        toastr.warning('@TempData["UpdateSucess"]', { timeOut: 5000 });
    </script>
}

InvoicingApplication/Views/Shared/_UsersLayout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - InvoicingApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboardStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InvoicingApplication.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body onload="window.history.forward();">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="DashboardPage">InvoicingApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Dashboard" asp-action="ContactUs">
                                Contact Us
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mx-5 ">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Profile</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item btn btn-link" asp-route-id="@ViewBag.Id" asp-controller="User" asp-action="Edit">@ViewBag.Email</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item btn btn-danger" asp-controller="Identity" asp-action="LoginPage">Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InvoicingApplication/Views/Shared/_dashboardLayout.cshtml
@using Microsoft.AspNetCore.Http

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - InvoicingApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/dashboardStyle.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InvoicingApplication.styles.css" asp-append-version="true" />
</head>
<body onload="window.history.forward();">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dashboard" asp-action="DashboardPage">InvoicingApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Dashboard" asp-action="ContactUs">
                                Contact Us
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                    </ul>
                    <ul class="navbar-nav mx-5 ">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Profile</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item btn btn-link" asp-route-id="@ViewBag.Id" asp-controller="User" asp-action="Edit">@ViewBag.Email</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item btn btn-danger" asp-controller="Identity" asp-action="LoginPage">Logout</a>
                            </div>  
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted fixed-bottom " style="height:100px;">
        <div class="container">
            &copy; 2022 - InvoicingApplication
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>